### ISSUE TITLE
Caractères accentués non pris en compte

### ISSUE THREAD

**Issue by Pyanne** [matthgyver/Arduino-Keyboard-FR#1]
Je n'arrive pas à faire fonctionner cette bibliothèque. Dès que je mets un caractère accentué dans Keybord.print la ligne entière n'est pas envoyée.
Le sketch ci-dessous tappe "**hello world**" alors qu'il devrait tapper "**hello élève world**":

`#include <KeyboardFR.h>

void setup()
{
delay(4000);
Keyboard.print("hello ");
Keyboard.print("élève ");
Keyboard.print("world");
}
void loop() {}`

**Comment by matthgyver** [comment]
Quel est l'OS cible ?
Tous les caractères accentués sont concernés ? Que donne un test individuel sur chaque caractère ? 

`
#include <KeyboardFR.h>

void setup()
{
delay(4000);
Keyboard.print("é");
Keyboard.print("è");
Keyboard.print("à");
# ...
}
void loop() {}
`

**Comment by nico7885** [comment]
Votre code ne peut pas fonctionner en l'état pour l'IDE Arduino qui utilise UTF-8, je suppose donc que vous utilisez un autre éditeur, pouvez vous nous dire lequel?

**Comment by matthgyver** [comment]
J'utilise VSCode avec le plugin Arduino

**Comment by nico7885** [comment]
Merci, j'ai fouillé un peu, votre éditeur doit être onfiguré pour de l' ascii étendu sinon je ne vois pas comment cela peut fonctionné.

**Comment by matthgyver** [comment]
Mon VScode est bien configuré en UTF-8.
Je viens de réinstaller mon PC et ai constaté quelques problèmes liés au fait que la saisie envoyée par la méthode ``Keyboard.write`` est trop rapide.
J'ai rajouté 10ms de délais entre chaque frappe et tout est rentré dans l'ordre. Cette version modifiée est ici :https://github.com/matthgyver/Arduino-Keyboard-FR/tree/slowdown-speed
