### ISSUE TITLE
ENTER et CTRL interprété en caractères 

### ISSUE THREAD

**Issue by 7h30th3r0n3** [matthgyver/Arduino-Keyboard-FR#2]
Salut , 

merci pour le travail, c'est génial !!! 

j'ai un petit problème cependant , lors de l'utilisation de la commande ENTER ou CTRL dans mon script wifiducky.

quand la commande else if (b.equals("CTRL")) Keyboard.press(KEY_LEFT_CTRL);  est demandé c'est le symbole € qui est interprété,
quand la commande (b.equals("ENTER")) Keyboard.press(KEY_RETURN); est demandé c'est le symbole ° qui est interprété,

 c'est dommage car toutes les autres touches semble fonctionner , 
mais je pense que le problème vient du bind des touches dans KeyboardFR.h , car quand je change la valeur il m'affiche un autre caractères mais je n'arrive pas à trouver le bon layout de clavier qui correspond,

si jamais tu as la solution je suis preneur

**Comment by matthgyver** [comment]
Salut,
Ca me semble étrange. Quel est l'OS cible ?

N'y aurait-il pas d'autres touches 'appuyées' au moment ou tu appelles la méthode 'press' ?

Tu peux essayer un 'releaseAll' avant le 'press' pour forcer le relâchement.

**Comment by cth-latest** [comment]
Je confirme que j'ai le même problème, la touche KEY_RETURN est interprété avec un caractère: °. J'ai essayer de releaseAll avant mais le même résultat. D'ailleurs j'ai essayer avant la lib original en querty, et la touche entrer marche correctement donc il, je suppose un problème avec cette lib

**Comment by cth-latest** [comment]
@matthgyver J'ai pu tester sur plusieurs WIndows et le résultat est le même partout. Il y a sûrement un problème de mapping dans la version FR

**Comment by matthgyver** [comment]
Je viens de faire quelques modifs et vous invite à tester la version présente dans la branche [fix-issue-2](https://github.com/matthgyver/Arduino-Keyboard-FR/tree/fix-issue-2)

Je n'ai pas rencontré le soucis car j'utilise cette librairie d'une autre manière. Je n'ai donc pas de quoi tester rapidement.
Pouvez-vous me faire un retour svp ?

**Comment by cth-latest** [comment]
@matthgyver Après avoir tester le fix, il semblerai que le problème ne soit toujours pas fix. Cela a d'ailleurs casser la touche windows (KEY_LEFT_GUI)

**Comment by matthgyver** [comment]
@Velka-DEV Peux-tu tester à nouveau ?
Les modifs apportées nécessitent de retester toutes les combinaisons faisant appel à un modifier (CTRL,ALT ...) et les touches non alpha numériques (ENTER, TAB, PAGEUP, UPARROW ...)

**Comment by cth-latest** [comment]
Il semblerait que les touches soit maintenant correctement interprété mais la fonction Keyboard.release(key) ne relache plus correctement la touche.

**Comment by cth-latest** [comment]
@matthgyver Mais le binding des touches me semblent OK ducoup, reste à fix la fonction de release

**Comment by matthgyver** [comment]
@Velka-DEV je viens de faire quelques ajustements et pense que ça doit être OK désormais

**Comment by cth-latest** [comment]
@matthgyver Désolé pour le temps de réponse, oui ça à l'air d'être réglé. Merci pour ton travail

**Comment by 7h30th3r0n3** [comment]
Hello ! le temps passe trop vite et mes mails ne sont pas tous synchronisé ! 

c'est super !  je vois que ça à pas mal avancé ! désolé de ne pas avoir était dispo pour les tests ...

 je vais tester pour faire un double retour, 

encore merci pour le taf !

**Comment by 7h30th3r0n3** [comment]
Après plusieurs test , je n'ai relevé qu'une erreur d’interprétation sur les caractères % qui stop l’exécution du script et ù qui supprime le caractères suivant , sinon tout semble ok !

ça peut être utile pour les chemins type : %HOMEPATH%/Desktop  

Edit : apparemment le caractères & bloque aussi l’exécution du script

**Comment by mdrbx** [comment]
Je déterre aussi ce topic car malgré les modifs proposées le caps lock ne fonctionne pas non plus. Quelqu'un aurait il une idée ?

**Comment by cth-latest** [comment]
Vous devriez crée une nouvelle issue car celle ci est lier au CRTL + ENTER, les patch n'était que pour ces deux touches.
