### ISSUE TITLE
Impossible d'utiliser le CAPS LOCK

### ISSUE THREAD

**Issue by mdrbx** [matthgyver/Arduino-Keyboard-FR#3]
J'essaie de remapper le code pour pouvoir faire fonctionner le caps lock mais impossible chez moi.
Mes connaissances dans le sujet sont limitées malheureusement je tatone mais je n'ai rien de probant pour fixer ce problème.

**Comment by matthgyver** [comment]
Que donne 
```#define KEY_CAPS_LOCK		0x39```
à la place de 
```#define KEY_CAPS_LOCK		0xC1```
dans le fichier ``keyboard.h``

**Comment by mdrbx** [comment]
Cela imprime des "9" ou des "ç" si le caps lock est déjà actif.

Pardon de mon ignorance, mais comment peux t'on connaitre justement le mappage en l'avance ? N'y a t'il aucune ressource à ce sujet ?
Je préfèrerais largement proposer un pull request :).

**Comment by mdrbx** [comment]
Trouvé ! Voici le code :
`#define KEY_CAPS_LOCK		0x14`
